apiVersion: v1
kind: Service
metadata:
  name: app-clusterip-svc
spec:
  # The type of Service is ClusterIP, and not NodePort, as it will be
  # accessible to outside world.
  type: ClusterIP
  # Get the selector so that this service knows, what set of Pod, it
  # supposed to be providing access to. In order to properly select to
  # the client deployment, so look for the templates->label->component
  selector: 
    component: java-app
  ports:    
    - port: 8086
      # 'port' is the service port and 
      # 'targetPort' is the container port where the java service is running
      targetPort: 8086
      # There is no nodePort for the outside world, I will create an
      # Ingress Service wherein I will add the nodePort, so that 
      # external world can connect to.



