apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: java-app
  template:
    metadata:
      label:
        component: java-app
    spec:
      containers:
        - name: users-app
          image: kuvivek/users-mysql:0.1.0
          ports:
            - containerPort: 8181


