version: '3.1'
services:
  users-mysql:
    image: kuvivek/users-mysql:0.1.0
    ports:
      - "8086:8086"
    networks:
      - internal
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql-standalone
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url": "jdbc:mysql://mysql-standalone:3306/test",
    }'

  mysql:
    image: mysql:5.6 
    container_name: mysql-standalone
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
    networks:
      - internal

networks:
  internal:
