apiVersion: v1 
kind: ConfigMap 
metadata:
  name: javaapp-configmap 
data:
  # set as complete file contents (even JSON!)
  keys: | 
    spring.datasource.url=jdbc:mysql://mysql-standalone:3306/test
