apiVersion: v1
kind: Pod
metadata:
  name: mysql-db-pod
  labels:
    component: mysql-db
spec:
  containers:
    - name: "mysql-standalone"
      image: mysql:5.6
      env:
       - name: "MYSQL_USER" 
         value: "sa"
       - name: "MYSQL_PASSWORD"
         value: "password"
       - name: "MYSQL_ROOT_PASSWORD"
         value: "password"
       - name: "MYSQL_DATABASE"
         value: "test"
      ports:
       - containerPort: 3306
      volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: mysql-initdb
      configMap:
        name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE TABLE users (id INT, name VARCHAR(256), salary INT, teamName VARCHAR(256));
    INSERT INTO test VALUES (1, 'Sam', 3400, 'Development');
