apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql-db
  template:
    metadata:
      labels:
        component: mysql-db
    spec:
      hostname: mysql-standalone
      containers:
        - name: mysql-standalone
          image: mysql:5.6
          env:
            - name: "MYSQL_USER" 
              value: "sa"
            - name: "MYSQL_PASSWORD"
              value: "password"
            - name: "MYSQL_ROOT_PASSWORD"
              value: "password"
            - name: "MYSQL_DATABASE"
              value: "test"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
              
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE TABLE users (id INT, name VARCHAR(50), salary INT, teamName VARCHAR(50));
    INSERT INTO users VALUES (1, 'Vivek Kumar', 4900, 'DevOps');
