apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql-db
  template:
    metadata:
      labels:
        component: mysql-db
    spec:
      containers:
        - name: mysql-standalone
          image: mysql:5.6
          env:
            - name: "MYSQL_USER" 
              value: "sa"
            - name: "MYSQL_PASSWORD"
              value: "password"
            - name: "MYSQL_ROOT_PASSWORD"
              value: "password"
            - name: "MYSQL_DATABASE"
              value: "test"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
              
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE TABLE test (id INT, name VARCHAR(256), age INT, gender VARCHAR(3));
    INSERT INTO test VALUES (1, 'Vivek Kumar', 39, 'm');
