apiVersion: v1
kind: Pod
metadata:
  name: mysql-db-pod
  labels:
    component: mysql-db
spec:
  containers:
    - name: mysqldb-standalone
      image: mysql:5.6
      env:
       - name: MYSQL_USER 
         value: sa
       - name: MYSQL_PASSWORD
         value: password
       - name: MYSQL_ROOT_PASSWORD
         value: password
       - name: MYSQL_DATABASE
         value: test
      ports:
       - containerPort: 3306
